### ISSUE TITLE
New user issues

### ISSUE THREAD

**Issue by etyurin** [nyoom-engineering/nyoom.nvim#82] opened 2022-12-06 03:45 UTC
Hi! Great config, congratulations, - just wish there were a few more examples, even if inside the code to help fennel/neovim newbies like myself.

- Looks like a typo in tools/lsp/config.fnl: need to have clojure_lsp vs clojure-lsp
- tools/debugger/config.fnl: those of us using conda, need to replace python location in dap-python. Is it really the best way to refer to an environmental variable as `(vim.fn.expand :$CONDA_PYTHON_EXE)` ?
- How do I move the config change above into user-level config.fnl that does not get overwritten?

**Comment by shaunsingh** [comment] 2022-12-09 01:24
> Looks like a typo in tools/lsp/config.fnl: need to have clojure_lsp vs clojure-lsp

Thanks, should be fixed now 

> Tools/debugger/config.fnl: those of us using conda, need to replace python location in dap-python. 

In your `config.fnl` (which can now also be found under `~/.config/nyoom/config.fnl` you can use the `after` function to override builtin configurations. The issue is `dap-python` is quite annoying because it doesn't use a table for configuration. For now, sadly the only way would be to manually modify the above variable

The new update redid quite a bit of the debugger module, so I'd like to hear your thoughts and experience with it, and if you'd like anything to be changed or improved 

> How do I move the config change above into user-level config.fnl that does not get overwritten?

 Sadly for now it isn't possible, most likely I'll PR to `dap-python` to add an option to configure it through a lua table

> Is it really the best way to refer to an environmental variable as (vim.fn.expand :$CONDA_PYTHON_EXE)

You can use `os.getenv` to get the value of an env variable or use `vim.fn.expand` as you have, either works

**Closed** 2023-03-20 20:29 UTC
